import Script from 'next/script';
import '@/public/bootstrap.min.css';
import '@/public/incrementalCounter/jquery.incremental-counter.css';
import './globals.css';

export const metadata = {
  title: 'Friend Finder | A Complete Social Network',
  description: 'Generated by Websadroit'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Script src={"/jquery/jquery-3.7.0.min.js"} /> {/* Import jQuery */}
        <Script src={"/bootstrap.bundle.min.js"} /> {/* Import Bootstrap JS */}
        <Script src={"/sweetalertPopup/sweetalert2.all.min.js"} /> {/* Import SweetalertPopup JS */}
        <Script src={"/incrementalCounter/jquery.incremental-counter.js"} /> {/* Import Incremental Counter */}
        <Script src={"/js/mainScript.js"} /> {/* Import Custom Script */}
      </body>
    </html>
  )
}

